Repository open-horizon/open-horizon.github.io, pull requests merged in 2022-05, with the labels that each got.

#248 Issue-247: document_conventions.md lint fixes
  docs/getting_started/document_conventions.md
Labels: documentation

#246 Issue-245: Excluded two files
  .github/workflows/orphan_pages_checker.yml
Labels: bug

#254 Issue-253: updated GHP config to remove files from page gen
  _config.yml
Labels: automation

#264 Issue-263: Add ppc64le keyword
  _data/keyword.yml
Labels: enhancement, dependencies
