Repository open-horizon/open-horizon.github.io, pull requests merged in 2022-03, with the labels that each got.

#199 Issue-140 (Chore): Updated Open Graph image metadata
  _config.yml
  _includes/ogmeta.html
  img/hero-dark-site.png
Labels: documentation, enhancement, automation

#208 Issue-204: Agbot keyword variable fixes
  _data/keyword.yml
  docs/api/agbot_api.md
  docs/developing/secrets_details.md
  docs/getting_started/faq.md
  docs/hub/cluster_sizing.md
  docs/installing/edge_clusters.md
  docs/installing/edge_devices.md
  docs/installing/exchange_api.md
  docs/troubleshoot/index.md
  docs/user_management/rbac.md
  docs/user_management/security_privacy.md
  docs/using_edge_services/service_rollbacks.md
Labels: documentation

#217 Issue-214 (bug): Added missing link to `_config.yml` file
  _config.yml
  _includes/ogmeta.html
Labels: bug
