Repository open-horizon/open-horizon.github.io, pull requests merged in 2023-03, with the labels that each got.

#463 Issue-462: Fixing broken link
  docs/index.html
Labels: documentation, doc: non-technical

#465 Issue 348 - Adding explanation on docs source repo
  README.md
Labels: doc: non-technical

#468 Issue-467: External link glyph friendly to dark mode
  _sass/color_schemes/dark.scss
  img/launch-glyph.svg
Labels: documentation, doc: non-technical

#471 Issue-464: Updating orphan pages checker due to ruby errors
  .github/workflows/orphan_pages_checker.yml
Labels: doc: technical

#473 Issue-464: Updating orphan pages checker due to ruby errors
  .github/workflows/orphan_pages_checker.yml
Labels: doc: technical

#478 Issue-459: remove old FAQ and fix any links
  _config.yml
  _posts/2020-08-18-restart-agent.md
  _posts/2020-08-19-sample-faq.md
  _posts/2020-08-20-dedicated-network-between-services.md
  _posts/2020-08-24-installation-requirements.md
  faq/index.html
  faq/search_data.json
Labels: doc: non-technical

#488 Issue 480: Create two columns on the Docs page
  Gemfile.lock
  docs/index.html
Labels: doc: non-technical
